version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

defaults: &defaultImage
  docker:
    - image: circleci/node:13.8.0

jobs:
  save_hello_world_output:
    <<: *defaultImage
    # docker:
    #   - image: circleci/node:13.8.0
  steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    <<: *defaultImage
    # docker:
    #   - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  
  my_job:
    <<: *defaultImage
    # docker:
    #   - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  
  failed_job_response:
    <<: *defaultImage
    steps:
      - run: exit 1
      - run: 
          name: on error
          command: echo "Hello Error!"
          when: on_fail
    

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - my_job:
          requires: 
            - print_output_file
            - save_hello_world_output
      - failed_job_response